#!/bin/sh

[ -r /etc/lsb-release ] && . /etc/lsb-release
[ -r /etc/custom-os-release ] && . /etc/custom-os-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

printf "Welcome to %s %s (%s %s)\n" "$OS_NAME" "$OS_VERSION" "$DISTRIB_DESCRIPTION" "$(uname -r)" 
