#!/bin/bash

if [[ ! $EUID -eq 0 ]]; then
    echo "Please run this script as root."
    exit 1
fi

echo "WARNING! This script will disable the Access Point and DHCP/DNS server. " \
"It will also let the Network Manager manage the wlan interface."
read -p "Are you sure you want to continue [y/N]? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then exit 1; fi

systemctl disable --now dnsmasq
systemctl disable --now hostapd

mv -v /etc/netplan/20-wlan-ap.yaml /etc/netplan/20-wlan-ap.yaml.ignore
netplan apply
