#!/bin/bash

if [[ ! $EUID -eq 0 ]]; then
    echo "Please run this script as root."
    exit 1
fi

echo "WARNING! This script will disable the Access Point and DHCP/DNS server. " \
"It will also let the Network Manager manage wlan_ext and eth0 interfaces."
read -p "Are you sure you want to continue [y/N]? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then exit 1; fi

systemctl disable --now dnsmasq
systemctl disable --now hostapd

sed -i 's|\(^.*lan.*$\)|# \1|' /etc/hosts

mv -v /etc/netplan/10-wlan-eth-bridge.yaml /etc/netplan/10-wlan-eth-bridge.yaml.ignore
netplan apply
