#!/bin/bash 

if [[ ! $EUID -eq 0 ]]; then
    echo "Please run this script as root."
    exit 1
fi

mv -v /etc/netplan/20-wlan-ap.yaml.ignore /etc/netplan/20-wlan-ap.yaml
netplan apply

systemctl enable --now hostapd
systemctl enable --now dnsmasq
