# Creates a bridge interface and configures ethernet interface.
network:
  version: 2
  ethernets:
    eth0:
      renderer: networkd
      dhcp4: true
  bridges:
    br0:
      renderer: networkd
      interfaces: []
      addresses: [ 10.0.0.1/24 ]
      link-local: []
