#!/bin/bash

source /etc/ros/setup.bash

UROS_AGENT_ARGS=${UROS_AGENT_ARGS:="serial -D /dev/serial0 -b 460800"}

export XRCE_DOMAIN_ID_OVERRIDE=${ROS_DOMAIN_ID:=0}

exec ros2 run micro_ros_agent micro_ros_agent ${UROS_AGENT_ARGS}
